import { v4 as uuidv4 } from "uuid";

export const FOUNDER_DATA = {
  name: "Mobidul Haque",
  title: "Founder & Land Donor",
  description:
    "May Allah grant him Jannatul Firdaus. His generosity and dedication built this mosque in 1980, serving as a beacon of faith for our community. His legacy continues to inspire us every day.",
  image: "/committee/mobidul_haque.png",
  pray: "Allahummaghfir lahu warhamhu wa a'izhhu wa'fu anhu",
};

export const ALL_COMMITTEE = [
  {
    id: uuidv4(),
    name: "জনাব মোঃ মোমিনুল হক",
    position: "Mutawalli",
    phone: "01300-842702",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "আলহাজ মোঃ মোফাজ্জেল হোসেন",
    position: "President",
    phone: "01718-965813",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ শফিকুল ইসলাম জুয়েল",
    position: "Senior Vice President",
    phone: "01711-308508",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মাহবুব আলম",
    position: "Vice President",
    phone: "01733-224858",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব আলহাজ শেখ আব্দুল জলিল",
    position: "Vice President",
    phone: "01716-952104",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনান আলহাজ্বা মোঃ গাউসুল হক",
    position: "Vice President",
    phone: "",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব অ্যাডঃ এস এম শরিফুল ইসলাম",
    position: "Vice President",
    phone: "01912-067684",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আব্দুল আলীম",
    position: "General Secretary",
    phone: "01911-935762",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ কামরুল ইসলাম",
    position: "Joint General Secretary",
    phone: "01712-334021",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আহসান হাবীব বাবু",
    position: "Assistant Joint General Secretary",
    phone: "01673-042174",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ ওবায়দুল্লাহ লিটন",
    position: "Treasurer",
    phone: "01711-137688",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ সাইফুল ইসলাম",
    position: "Member",
    phone: "01711-224467",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জিল্লুর রহমান",
    position: "Member",
    phone: "01914-222883",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ হারুনুর রশিদ",
    position: "Member",
    phone: "01712-140656",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আবুল কালাম আজাদ",
    position: "Member",
    phone: "01712-054593",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ শফিকুল ইসলাম",
    position: "Member",
    phone: "01715-422894",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আমিনুল হক",
    position: "Member",
    phone: "01718-622998",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ ইউনুস আলী ভূঁইয়া",
    position: "Member",
    phone: "01711-903670",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ লুৎফর রহমান",
    position: "Member",
    phone: "01715-081912",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ তৌহিদুল ইসলাম",
    position: "Member",
    phone: "01712-211464",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জহিরুল হক ভূঁইয়া",
    position: "Member",
    phone: "01711-193437",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ নজরুল ইসলাম বাদল",
    position: "Member",
    phone: "01715-333034",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মোশাররফ হোসেন ভূঁইয়া",
    position: "Member",
    phone: "01712-231168",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ সাইদুর রহমান",
    position: "Member",
    phone: "01711-042851",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মজিবুর রহমান",
    position: "Member",
    phone: "01912-225301",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ বিল্লাল হোসেন",
    position: "Member",
    phone: "01732-263233",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মিজানুর রহমান",
    position: "Member",
    phone: "01711-385077",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ নাজমুল হোসেন ভূঁইয়া",
    position: "Member",
    phone: "01711-073868",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মনির হোসেন",
    position: "Member",
    phone: "01711-155829",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ সিরাজুল ইসলাম",
    position: "Member",
    phone: "01715-021950",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আতিকুর রহমান",
    position: "Member",
    phone: "01711-364245",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ কামাল হোসেন",
    position: "Member",
    phone: "01711-203753",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আবুল কালাম (অপু)",
    position: "Member",
    phone: "01715-018610",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মমিনুল হক মিনু",
    position: "Member",
    phone: "01711-344265",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আবুল কাসেম ভূঁইয়া",
    position: "Member",
    phone: "01712-163456",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জহিরুল ইসলাম মন্টু",
    position: "Member",
    phone: "01914-257602",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জাকির হোসেন ভূঁইয়া",
    position: "Member",
    phone: "01711-454593",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আব্দুল আজিজ ভূঁইয়া",
    position: "Member",
    phone: "01716-168128",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জাকির হোসেন",
    position: "Member",
    phone: "01711-827252",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ কাইয়ুম হোসেন",
    position: "Member",
    phone: "01716-042851",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ রফিকুল ইসলাম",
    position: "Member",
    phone: "01711-137688",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ লিয়াকত আলী ভূঁইয়া",
    position: "Member",
    phone: "01911-308508",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আক্তার হোসেন মাসুম",
    position: "Member",
    phone: "01711-975936",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ শফিকুল ইসলাম শফিক",
    position: "Member",
    phone: "01732-230006",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মজিবুর রহমান",
    position: "Member",
    phone: "01715-412586",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আবুল কালাম",
    position: "Member",
    phone: "01711-026046",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ কামাল হোসেন ভূঁইয়া",
    position: "Member",
    phone: "01712-259160",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ ইব্রাহিম খলিল ভূঁইয়া",
    position: "Member",
    phone: "01711-133519",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আলমগীর হোসেন ভূঁইয়া",
    position: "Member",
    phone: "01711-042137",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ মাহফুজুর রহমান",
    position: "Member",
    phone: "01711-155829",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জহিরুল ইসলাম মাসুম",
    position: "Member",
    phone: "01711-447545",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আসাদুজ্জামান",
    position: "Member",
    phone: "01716-465494",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ জহিরুল ইসলাম মন্টু",
    position: "Member",
    phone: "01712-067684",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ সাইদুল ইসলাম সাঈদ",
    position: "Member",
    phone: "01711-203753",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ শরিফুল ইসলাম",
    position: "Member",
    phone: "01715-021950",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ হারুনুর রশিদ",
    position: "Member",
    phone: "01711-364245",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ ইসমাইল হোসেন",
    position: "Member",
    phone: "01711-137688",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আব্দুল মান্নান",
    position: "Member",
    phone: "01711-454593",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ শাহ আলম ভূঁইয়া",
    position: "Member",
    phone: "01711-155829",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "জনাব মোঃ আব্দুল মালেক",
    position: "Member",
    phone: "01733-073295",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "শেখ ওয়াহিদুজ্জামান (মিকুন)",
    position: "Member",
    phone: "01711-814400",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "মোঃ আরিফুল ইসলাম",
    position: "Member",
    phone: "01781-409475",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
  {
    id: uuidv4(),
    name: "মোঃ মিজানুর রহমান নোভা",
    position: "Member",
    phone: "01920-688190",
    avatar: "/committee/placeholder.jpg",
    status: "current",
  },
];
