export const FOUNDER_DATA = {
  name: "Mobidul Haque",
  title: "Founder & Land Donor",
  description:
    "May Allah grant him Jannatul Firdaus. His generosity and dedication built this mosque in 1980, serving as a beacon of faith for our community. His legacy continues to inspire us every day.",
  image: "/mobidul_haque.png",
  pray: "Allahummaghfir lahu warhamhu wa a'izhhu wa'fu anhu",
};

export const ALL_COMMITTEE = [
  // Current Members (status: "current")
  {
    id: 1,
    name: "Md. Abdul Hai",
    position: "President",
    phone: "+880 1911935762",
    avatar: "/committee/president.jpg",
    status: "current",
  },
  {
    id: 2,
    name: "Md. Ali Hossain",
    position: "Vice President",
    phone: "+880 1712345678",
    avatar: "/committee/vice-president.jpg",
    status: "current",
  },
  {
    id: 3,
    name: "Md. Rahman",
    position: "General Secretary",
    phone: "+880 1812345678",
    avatar: "/committee/secretary.jpg",
    status: "current",
  },
  {
    id: 4,
    name: "Md. Islam",
    position: "Treasurer",
    phone: "+880 1912345678",
    avatar: "/committee/treasurer.jpg",
    status: "current",
  },
  {
    id: 5,
    name: "Md. Kamal Hossain",
    position: "Assistant Secretary",
    phone: "+880 1612345678",
    avatar: "/committee/asst-secretary.jpg",
    status: "current",
  },
  {
    id: 6,
    name: "Mominul Haque",
    position: "Mutawalli",
    phone: "+880 1300842702",
    avatar: "/committee/mutawalli.jpg",
    status: "current",
  },
  {
    id: 7,
    name: "Md. Rafiq Islam",
    position: "Committee Member",
    phone: "+880 1512345678",
    avatar: "/committee/member1.jpg",
    status: "current",
  },
  {
    id: 8,
    name: "Md. Faruk Ahmed",
    position: "Committee Member",
    phone: "+880 1712345679",
    avatar: "/committee/member2.jpg",
    status: "current",
  },
  {
    id: 9,
    name: "Md. Liton Mia",
    position: "Committee Member",
    phone: "+880 1812345679",
    avatar: "/committee/member3.jpg",
    status: "current",
  },
  {
    id: 10,
    name: "Md. Josim Uddin",
    position: "Imam",
    phone: "+880 1912345670",
    avatar: "/committee/imam.jpg",
    status: "current",
  },
  {
    id: 11,
    name: "Md. Azhar Uddin",
    position: "Khateeb",
    phone: "+880 1612345670",
    avatar: "/committee/khateeb.jpg",
    status: "current",
  },
  // Former Members (status: "former") - Left position but alive
  {
    id: 12,
    name: "Md. Hafizur Rahman",
    position: "Former President (2015-2020)",
    phone: "+880 1911111111",
    avatar: "/committee/former1.jpg",
    status: "former",
  },
  {
    id: 13,
    name: "Md. Shahidul Islam",
    position: "Former Secretary (2018-2022)",
    phone: "+880 1811111111",
    avatar: "/committee/former2.jpg",
    status: "former",
  },
  {
    id: 14,
    name: "Md. Jalal Uddin",
    position: "Former Treasurer (2010-2015)",
    phone: "+880 1711111111",
    avatar: "/committee/former3.jpg",
    status: "former",
  },
  {
    id: 15,
    name: "Md. Babul Mia",
    position: "Former Committee Member (2015-2020)",
    phone: "+880 1611111111",
    avatar: "/committee/former4.jpg",
    status: "former",
  },
  // Deceased Members (status: "deceased") - Passed away
  {
    id: 16,
    name: "Mobidul Haque",
    position: "Founder, First President & Mutawalli (1980-1998)",
    avatar: "/committee/founder.jpg",
    status: "deceased",
  },
  {
    id: 17,
    name: "Shahidul Haque",
    position: "Former Mutawalli (1998-2020)",
    avatar: "/committee/past1.jpg",
    status: "deceased",
  },
  {
    id: 18,
    name: "Md. Abdur Rahim",
    position: "Former Treasurer (1985-2000)",
    avatar: "/committee/past2.jpg",
    status: "deceased",
  },
  {
    id: 19,
    name: "Md. Solaiman",
    position: "Former President (2000-2010)",
    avatar: "/committee/past3.jpg",
    status: "deceased",
  },
  {
    id: 20,
    name: "Md. Yousuf Ali",
    position: "Former Secretary (2005-2015)",
    avatar: "/committee/past4.jpg",
    status: "deceased",
  },
];
